# Generated by Django 5.1.1 on 2024-10-25 19:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_video_author_alter_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[core.models.validate_no_special_characters],
                verbose_name="Nome",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(
                validators=[core.models.validate_no_special_characters],
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.SlugField(
                unique=True, validators=[core.models.validate_no_special_characters]
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[core.models.validate_no_special_characters],
                verbose_name="Título",
            ),
        ),
        migrations.AlterField(
            model_name="videomedia",
            name="video_path",
            field=models.CharField(
                max_length=255,
                validators=[core.models.validate_file_path],
                verbose_name="Vídeo",
            ),
        ),
    ]
